export const ADD_PAKET = 'ADD_PAKET';
export const PAKET_FAILED = 'PAKET_FAILED'
export const PAKET_LOADING = 'PAKET_LOADING';

export const ADD_CUSTOM = 'ADD_CUSTOM';
export const CUSTOM_FAILED = 'CUSTOM_FAILED'
export const CUSTOM_LOADING = 'CUSTOM_LOADING';

export const ADD_IKLAN = 'ADD_IKLAN';
export const IKLAN_FAILED = 'IKLAN_FAILED'
export const IKLAN_LOADING = 'IKLAN_LOADING';


export const ADD_PAKETDETAIL = 'ADD_PAKETDETAIL';
export const PAKETDETAIL_FAILED = 'PAKETDETAIL_FAILED'


export const ADD_BLOG = 'ADD_BLOG';
export const BLOG_FAILED = 'BLOG_FAILED'
export const BLOG_LOADING = 'BLOG_LOADING';


export const ADD_PROMO = 'ADD_PROMO';
export const PROMO_FAILED = 'PROMO_FAILED'
export const PROMO_LOADING = 'PROMO_LOADING';

export const ADD_PESANPAKET = 'ADD_PESANPAKET';
export const PESANPAKET_FAILED = 'PESANPAKET_FAILED'
export const PESANPAKET_LOADING = 'PESANPAKET_LOADING';


export const ADD_PESANCUSTOM = 'ADD_PESANCUSTOM';
export const PESANCUSTOM_FAILED = 'PESANCUSTOM_FAILED'
export const PESANCUSTOM_LOADING = 'PESANCUSTOM_LOADING';


